
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 18 10:28:53 GMT 2013
//----------------------------------------------------

package uk.ac.ucl.comp2010.bestgroup;

/** CUP generated interface containing symbol constants. */
public interface QSym {
  /* terminals */
  public static final int LESSEQUALS = 47;
  public static final int DIVIDE = 38;
  public static final int POWER = 39;
  public static final int GREATEREQUALS = 48;
  public static final int CHAR = 8;
  public static final int CONCAT = 13;
  public static final int EQUALS = 44;
  public static final int GREATER = 46;
  public static final int CURLYBRACKETCLOSE = 20;
  public static final int REPEAT = 31;
  public static final int INT = 6;
  public static final int LESS = 45;
  public static final int EQUALSCOMPARISON = 43;
  public static final int MINUS = 36;
  public static final int NOT = 42;
  public static final int AND = 40;
  public static final int SEMICOLON = 10;
  public static final int TYPE = 3;
  public static final int OR = 41;
  public static final int IN = 33;
  public static final int TDEF = 23;
  public static final int BOOL = 5;
  public static final int COMMA = 11;
  public static final int BRACKETOPEN = 15;
  public static final int UNTIL = 32;
  public static final int PLUS = 35;
  public static final int IF = 27;
  public static final int TUPLELEFT = 21;
  public static final int DOT = 14;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int SQUAREBRACKETCLOSE = 18;
  public static final int error = 1;
  public static final int FDEF = 24;
  public static final int VOID = 25;
  public static final int TUPLERIGHT = 22;
  public static final int TIMES = 37;
  public static final int COLON = 12;
  public static final int BRACKETCLOSE = 16;
  public static final int ELSE = 28;
  public static final int SQUAREBRACKETOPEN = 17;
  public static final int WHILE = 29;
  public static final int FLOAT = 7;
  public static final int CURLYBRACKETOPEN = 19;
  public static final int LEN = 34;
  public static final int STRING = 9;
  public static final int CUSTOMTYPE = 4;
  public static final int DO = 30;
}

