
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 15 17:21:31 GMT 2013
//----------------------------------------------------

package uk.ac.ucl.comp2010.bestgroup;

/** CUP generated interface containing symbol constants. */
public interface QSym {
  /* terminals */
  public static final int LESSEQUALS = 35;
  public static final int DIVIDE = 28;
  public static final int POWER = 29;
  public static final int GREATEREQUALS = 36;
  public static final int EQUALS = 24;
  public static final int GREATER = 34;
  public static final int CURLYBRACKETCLOSE = 11;
  public static final int REPEAT = 20;
  public static final int LESS = 33;
  public static final int EQUALSCOMPARISON = 23;
  public static final int MINUS = 26;
  public static final int NOT = 32;
  public static final int SEMICOLON = 3;
  public static final int AND = 30;
  public static final int IN = 22;
  public static final int OR = 31;
  public static final int TDEF = 12;
  public static final int COMMA = 4;
  public static final int BRACKETOPEN = 6;
  public static final int UNTIL = 21;
  public static final int PLUS = 25;
  public static final int IF = 16;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int SQUAREBRACKETCLOSE = 9;
  public static final int error = 1;
  public static final int FDEF = 13;
  public static final int VOID = 14;
  public static final int TIMES = 27;
  public static final int COLON = 5;
  public static final int BRACKETCLOSE = 7;
  public static final int ELSE = 17;
  public static final int SQUAREBRACKETOPEN = 8;
  public static final int WHILE = 18;
  public static final int CURLYBRACKETOPEN = 10;
  public static final int DO = 19;
}

