
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 02 13:03:25 GMT 2013
//----------------------------------------------------

package uk.ac.ucl.comp2010.bestgroup;

/** CUP generated interface containing symbol constants. */
public interface QSym {
  /* terminals */
  public static final int error = 1;
  public static final int ANY = 2;
  public static final int EOF = 0;
}

